### ISSUE TITLE
Add option to show shortcuts

### ISSUE THREAD

**Issue by tusharf5** [natscale/react-calendar#2]
Shortcuts like "today", "selected", "range start", "range end", "toggle dates"

**Comment by tusharf5** [comment]
https://user-images.githubusercontent.com/11244314/117000627-a7eedb80-ace1-11eb-9d7c-152f4ce4e257.png

**Comment by tusharf5** [comment]
![](https://user-images.githubusercontent.com/11244314/117000627-a7eedb80-ace1-11eb-9d7c-152f4ce4e257.png)

**Comment by zutshiy** [comment]
Working on this.

**Comment by tusharf5** [comment]
This feature is available now.
