### ISSUE TITLE
auto submitted in <form> when changing date

### ISSUE THREAD

**Issue by hackcomj** [natscale/react-calendar#31]
When I use this Calendar component in &lt;form&gt; and select a date, it is auto submitted.
I looked at the html and found the date is &lt;button&gt; and no type speicified.
The default behavior of &lt;button&gt; is submit in HTML5, so it seems to happen.
Please put the type in &lt;button&gt; tag.
This should be good enough for this issue.
&lt;button type="button"&gt;

**Comment by tusharf5** [comment]
Thanks for reporting the issue. I will take a look at this during this weekend.

**Comment by tusharf5** [comment]
Hey @hackcomj We've pushed a fixed addressing your issue. 

It'd be great if you could give it a try. The latest version is `0.0.0-beta.16`.

Thanks.

**Comment by hackcomj** [comment]
@tusharf5 It's working well. Thank you very much. 
If you change in npm as well, it will help many people. (It is still 0.0.0-beta.8)
Thank you again.
