### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by UlrichMD** [natscale/react-calendar#36]
When runing the npm install command : 

`npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @natscale/react-calendar@0.0.0-beta.20
npm ERR! node_modules/@natscale/react-calendar
npm ERR!   @natscale/react-calendar@"*" from the root project`

**I think the dependencies need to be updated with React@18.0.0**

**Comment by tusharf5** [comment]
Working on it. Thanks

**Comment by tusharf5** [comment]
Try Now

**Comment by kavita615** [comment]
yarn add @natscale/react-calendar

yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-spring > @react-spring/konva@9.2.4" has unmet peer dependency "konva@>=2.6".
warning "react-spring > @react-spring/konva@9.2.4" has unmet peer dependency "react-konva@^16.8.0  || ^17.0.0".
warning "react-spring > @react-spring/native@9.2.4" has unmet peer dependency "react-native@>=0.58".
warning "react-spring > @react-spring/three@9.2.4" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "react-spring > @react-spring/three@9.2.4" has unmet peer dependency "three@>=0.126".
warning "react-spring > @react-spring/zdog@9.2.4" has unmet peer dependency "react-zdog@>=1.0".
warning "react-spring > @react-spring/zdog@9.2.4" has unmet peer dependency "zdog@>=1.0".
[4/4] 🔨  Building fresh packages...
[6/7] ⠈ @react-spring/core
[2/7] ⠈ fsevents
[3/7] ⠈ core-js
[-/7] ⠈ waiting...
error /node_modules/@natscale/react-calendar: Command failed.
Exit code: 1
Command: cd docs/ && yarn install && cd ..
Arguments: 
Directory: /node_modules/@natscale/react-calendar

**Comment by tusharf5** [comment]
I think I know the issue. Will be fixed by tonight. Thanks for the logs.

**Comment by tusharf5** [comment]
It is now fixed in the latest version now.
