### ISSUE TITLE
 Change language

### ISSUE THREAD

**Issue by CC25MC** [natscale/react-calendar#38]
Is there any way to change the language?

**Comment by tusharf5** [comment]
Could you describe what you're trying to do? If possible I can work on it this weekend.

**Comment by zhen1asemen1uk** [comment]
We try change language (translate local). For exemple : May(English) === Травень(Ukrainien)
How i can do it?

**Comment by tusharf5** [comment]
There's not a way to do it now but I can add it in the next few days. 

I'll update you here.

**Comment by tusharf5** [comment]
This is now possible with the latest release. Check here https://github.com/natscale/react-calendar/blob/main/CHANGELOG.md#000-beta24
